### ISSUE TITLE
Greenway Example

### ISSUE THREAD

**Issue by Ch4s3** [chb/sample_ccdas#12]
The greenway example is all one line and could use some formatting. I also think they have updated their ccda since this was posted. I'd be happy to update it if you're interested.

**Comment by jmandel** [comment]
Hi Chase,

The goal of this repository is to expose unaltered documents, to
demonstrate what developers can expect to see in the real world. So we
haven't applied any formatting or cleanup. In this case, Greenway supplied
a file all on one line (which is perfectly valid, though not
human-reader-friendly).

If you have access to a Greenway EHR and want to generate an additional
C-CDA (with sample data only, no protected health information) we'd be glad
to include that in addition to the current file. But please don't apply any
formatting -- we just want "the raw data" :-)

**Comment by Ch4s3** [comment]
Let me take a look and how different the CCDA is now and if post it. If I can, I'll put in a pull request.

**Comment by Ch4s3** [comment]
I can't post the new CCDA right now for the usual reasons, but may be able to in the future. If you're interested in chatting by e-mail about it or some of the other EHRs' CCDA implementations I be happy to share what I know.

**Comment by jmandel** [comment]
Absolutely. Feel free to reach out  to me directly (I'm `joshua.mandel`@`childrens.harvard.edu`).
