### ISSUE TITLE
SRS Software EHR Sample

### ISSUE THREAD

**Issue by stemithy** [chb/sample_ccdas#13]
I'm working with a client using an EHR called SRS (srssoft.com).  I was wondering if anyone had any samples involving this system specifically.  If not, I'll be sharing as soon as we start generating CCD files for our client.

Thank you.  What you have posted is extremely helpful.

**Comment by jmandel** [comment]
Great -- we have no examples from SRS and would be glad to include some here. Closing this issue for now, but please do contribute when you're ready!

**Comment by henryweimd** [comment]
Hi @stemithy do you know where I'd crawl around in the system to try to grab some CCDs or CCDAs?  I have access to a practice that runs this system but would need to carefully de-identify and sanitize the files.
