### ISSUE TITLE
ONC MU2 Test Data

### ISSUE THREAD

**Issue by seantbrady** [chb/sample_ccdas#8]
Does anyone have a CCDA document that matches the ONC test data here: http://www.healthit.gov/sites/default/files/170.314e1vdt_2014_td_approved_v1.2.pdf

**Comment by jmandel** [comment]
I forwarded your question to the team at NIST. They said:

> Sorry Josh,
> 
> There is no official samples for VDT Test scripts. The one that is provided by NIST for Transitions of Care should work for VDT purposes also.

**Comment by seantbrady** [comment]
Cool, thanks.  The test data for ToC doesn't match the test data for VDT.  In any case, it doesn't look like it's available.

**Comment by jmandel** [comment]
Agreed, the data don't match!
